// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp4SzrUXHfESdeaAE7QedzHTqlFaPJjM8',
    appId: '1:995959005078:web:69079be008abb3708847b7',
    messagingSenderId: '995959005078',
    projectId: 'tiktok-clone-9a9f7',
    authDomain: 'tiktok-clone-9a9f7.firebaseapp.com',
    storageBucket: 'tiktok-clone-9a9f7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA96VdH2AQyOp5LL0km_4NOH2xlNKFQzmw',
    appId: '1:995959005078:android:3842bf49b95141418847b7',
    messagingSenderId: '995959005078',
    projectId: 'tiktok-clone-9a9f7',
    storageBucket: 'tiktok-clone-9a9f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLa5_yTj3EVu0ukceIZ5iswqPKaHqvx14',
    appId: '1:995959005078:ios:73fb1c42bff4d0868847b7',
    messagingSenderId: '995959005078',
    projectId: 'tiktok-clone-9a9f7',
    storageBucket: 'tiktok-clone-9a9f7.appspot.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp4SzrUXHfESdeaAE7QedzHTqlFaPJjM8',
    appId: '1:995959005078:web:2d92d4ad5c6318358847b7',
    messagingSenderId: '995959005078',
    projectId: 'tiktok-clone-9a9f7',
    authDomain: 'tiktok-clone-9a9f7.firebaseapp.com',
    storageBucket: 'tiktok-clone-9a9f7.appspot.com',
  );
}
